### ISSUE TITLE
Some layer outputs are missing unit names

### ISSUE THREAD

**Issue by NSPECT** [NOAA-OCM/QNSPECT#64]
Some of the local pollutants dont show the units of their color scale (i.e., they don't have (mg) or (L)) when the Run Pollutant Analysis tool is run after loading it with the Load previous Analysis tool.  Very odd.

I've tried to attach a screen grab here.  The first group was created using the Run P Analysis Gui directly.  The second was after closing that GUI, then using the Load Previous funtion to reload that GUI.  Note that the Zinc and TSS local results NEVER had their units.

![image](https://user-images.githubusercontent.com/99758014/154341269-16128307-8d1a-4369-8326-76a069a0ab43.png)

**Comment by ar-siddiqui** [comment]
I have noticed odd behaviour of the styling and naming, both are the result of `postProcessorInterface`.

I don't think it is related to how you execute the algorithm, it is sometimes working and sometimes not. I tried `processing.execAlgorithmDialog()` directly and it had similar issues.

Tested on a completely new run and still, the issue persists.

I think this needs to push to QGIS itself as the code is remaining the same yet QGIS is behaving differently at each run.

**Comment by ar-siddiqui** [comment]
Dropping some thoughts here for future reference:
This issue might have occurred after moving run_aglrotihm class to the nested folder. 

- [x] Test at the following commit if the issue was still there or originated after one of the later commits  [2632463](https://github.com/Dewberry/QNSPECT/commit/2632463f70934a9afd93a3fa0c7e6bb285739137)
- [x] Test at the following commit as well  [ae1fce8](https://github.com/Dewberry/QNSPECT/commit/ae1fce85a9912bdbfed8fd6258939fa33b95083b)

**Comment by ar-siddiqui** [comment]
> Dropping some thoughts here for future reference: This issue might have occurred after moving run_aglrotihm class to the nested folder.
> 
> * [x]  Test at the following commit if the issue was still there or originated after one of the later commits  [2632463](https://github.com/Dewberry/QNSPECT/commit/2632463f70934a9afd93a3fa0c7e6bb285739137)
> * [x]  Test at the following commit as well  [ae1fce8](https://github.com/Dewberry/QNSPECT/commit/ae1fce85a9912bdbfed8fd6258939fa33b95083b)

Checked at both of these commits, the issue is reporducable at both of these commits.
